tested & fixed contact-us & newsletter
ooug/backend pull request #52
Opened 2021-04-21 16:05 UTC by avinashvidyarthi

- Tested newsletter & contact-us flow
- Added mailer credentials through .env file
- Added googleAccountKey.json file for blob uploads into gs bucket
- updated .gitignore & .env.example file

2021-04-22 16:17 UTC, InSantoshMahto requested changes
do the required changes

2021-04-22 16:17 UTC, InSantoshMahto commented on .env.example
> +GOOGLE_APPLICATION_CREDENTIALS="./googleAccountKeys.json" #path to key file
remove this

GOOGLE_APPLICATION_CREDENTIALS is not required in production or staging environment.
use this env only on local machine

2021-04-22 16:32 UTC, InSantoshMahto commented
added single space just after comment operators like # and //

example 

# your comments goes here
// js comments here ..

2021-04-23 12:24 UTC, avinashvidyarthi commented on .env.example
> +GOOGLE_APPLICATION_CREDENTIALS="./googleAccountKeys.json" #path to key file
Removed GOOGLE_APPLICATION_CREDENTIALS from .env.example file

2021-04-23 12:25 UTC, avinashvidyarthi commented
Removed GOOGLE_APPLICATION_CREDENTIALS from .env.example file

2021-04-23 13:21 UTC, InSantoshMahto approved these changes

2021-04-23 13:21 UTC, merged